# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 139a52957df242fbd8af742c6ce83f62395822e35a565a4c95a5164b08beb90ca69759a3f939fc2c5dca4b3fa49226328269f8881c243cd6af0cb5992ba378e6

test:
  secret_key_base: f517938aa55df519fe84be0d92444633cbfc2f4ee3892103cee44506893661398d898accaa94a678bed8ff9e8ae6384f6a5d4e7b3255ff9b2af99ce3ad46cc41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
